### ISSUE TITLE
Front-end bug with contract deployment

### ISSUE THREAD

**Issue by edison0xyz** [Zilliqa/Zilliqa-Wallet#42]
DeployContract button will be disabled if a contract does not have initialization parameters. 

The front-end code checks for whether the initialization parameters has been filled before enabling the "deploy" button. If the contract does not have init params, then the button can never be enabled and the user will hence not be able to deploy the code.

**Comment by AmritKumar** [comment]
@edisonljh Let’s fix this for the interim. But, ultimately, we will nuke Wallet IDE once we have web3.js and Truffle like developemnt and deployment framework.

**Comment by iantanwx** [comment]
Closing since we have robust programmatic tools for this purpose now.
