### ISSUE TITLE
Uncaught error during contract deployment

### ISSUE THREAD

**Issue by edison0xyz** [Zilliqa/Zilliqa-Wallet#43]
Uncaught error: `Contract state call failed: null` when trying to put events into the blockchain IDE.
App says contract is deployed, but it is not. Therefore causing the error. Something is making the blockchain IDE believe that the contract (which contains events) is deployed. 

However, it is not. Checked contract address using the curl commands and the contract address does not exist. 

**Cause:** Uncaught error with events. When we try to put events in the blockchain IDE, the page breaks. 

**Solution suggested:** Upgrade Scilla testnet to support events or better error catching mechanism

**Comment by AmritKumar** [comment]
I think this is because the binary on nodes isn’t up to date and hence does not recognise events.
